"""add stores and audit fields

Revision ID: b070393f3c7b
Revises: e4a26a86ebf9
Create Date: 2025-12-28 12:50:22.013384

"""

from typing import Sequence, Union
from uuid import uuid4

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "b070393f3c7b"
down_revision: Union[str, Sequence[str], None] = "e4a26a86ebf9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "stores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        sa.UniqueConstraint("uuid"),
    )

    op.add_column("skus", sa.Column("uuid", sa.Uuid(), nullable=True))
    op.add_column("skus", sa.Column("version", sa.Integer(), nullable=True))
    op.add_column("skus", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("skus", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.add_column("skus", sa.Column("deleted_at", sa.DateTime(), nullable=True))

    connection = op.get_bind()
    skus = connection.execute(sa.text("SELECT id FROM skus")).fetchall()
    for (sku_id,) in skus:
        connection.execute(
            sa.text("""UPDATE skus SET uuid = :uuid, version =1, created_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
                WHERE id = :id"""),
            {"uuid": str(uuid4()), "id": sku_id},
        )

    op.alter_column("skus", "uuid", nullable=False)
    op.alter_column("skus", "version", nullable=False)
    op.alter_column("skus", "created_at", nullable=False)
    op.alter_column("skus", "updated_at", nullable=False)
    op.create_unique_constraint("uq_skus_uuid", "skus", ["uuid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_skus_uuid", "skus", type_="unique")
    op.drop_column("skus", "deleted_at")
    op.drop_column("skus", "updated_at")
    op.drop_column("skus", "created_at")
    op.drop_column("skus", "version")
    op.drop_column("skus", "uuid")
    op.drop_table("stores")
    # ### end Alembic commands ###
