"""create skus table

Revision ID: e4a26a86ebf9 Revises:
Create Date: 2025-12-28 02:29:23.658530

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e4a26a86ebf9"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "skus",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sku", sa.String(), nullable=False),
        sa.Column("ean", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ean"),
        sa.UniqueConstraint("sku"),
    )

    # Seed initial SKUs
    op.bulk_insert(
        sa.table(
            "skus",
            sa.column("sku", sa.String),
            sa.column("ean", sa.String),
            sa.column("name", sa.String),
            sa.column("description", sa.String),
        ),
        [
            {"sku": "PAINT-WHT-1L", "ean": "5901234123457", "name": "White Paint 1L", "description": "Interior matt white"},
            {"sku": "PAINT-WHT-5L", "ean": "5901234123458", "name": "White Paint 5L", "description": "Interior matt white"},
            {"sku": "PAINT-BLK-1L", "ean": "5901234123459", "name": "Black Paint 1L", "description": "Interior matt black"},
            {"sku": "PAINT-RED-1L", "ean": "5901234123460", "name": "Red Paint 1L", "description": "Interior gloss red"},
            {"sku": "PRIMER-1L", "ean": "5901234123461", "name": "Primer 1L", "description": "Universal primer"},
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("skus")
    # ### end Alembic commands ###
